/*eslint comma-spacing: 0, key-spacing: 0, quotes: 0, quote-props: 0 */

const dummyUser = [{"username":"cwallace0","firstName":"Craig","lastName":"Wallace","email":"cwallace0@a8.net","phoneNumber":"1-(175)442-2407","isUser":true,"imageUrl":"http://dummyimage.com/153x114.bmp/ff4444/ffffff","password":"pIrLTLhH"},
{"username":"rroberts1","firstName":"Roger","lastName":"Roberts","email":"rroberts1@netvibes.com","phoneNumber":"57-(817)276-2036","isUser":false,"imageUrl":"http://dummyimage.com/104x101.png/cc0000/ffffff","password":"rPS7vf"},
{"username":"sfreeman2","firstName":"Sarah","lastName":"Freeman","email":"sfreeman2@google.ru","phoneNumber":"30-(504)805-5590","isUser":true,"imageUrl":"http://dummyimage.com/166x116.png/cc0000/ffffff","password":"c9ZAJGt2D9X"},
{"username":"jblack3","firstName":"Jeffrey","lastName":"Black","email":"jblack3@latimes.com","phoneNumber":"86-(602)457-6011","isUser":true,"imageUrl":"http://dummyimage.com/105x168.png/dddddd/000000","password":"z6Twb8AvJS"},
{"username":"jbishop4","firstName":"Jose","lastName":"Bishop","email":"jbishop4@xing.com","phoneNumber":"46-(827)656-6774","isUser":true,"imageUrl":"http://dummyimage.com/241x139.jpg/ff4444/ffffff","password":"JyOlqk"},
{"username":"msmith5","firstName":"Mildred","lastName":"Smith","email":"msmith5@spotify.com","phoneNumber":"92-(936)394-1861","isUser":false,"imageUrl":"http://dummyimage.com/204x165.bmp/cc0000/ffffff","password":"Cvivtdr6"},
{"username":"srobertson6","firstName":"Stephen","lastName":"Robertson","email":"srobertson6@nature.com","phoneNumber":"33-(661)180-1456","isUser":true,"imageUrl":"http://dummyimage.com/211x163.bmp/ff4444/ffffff","password":"WJ6lhDNUZ"},
{"username":"lcunningham7","firstName":"Lawrence","lastName":"Cunningham","email":"lcunningham7@naver.com","phoneNumber":"81-(203)726-9719","isUser":true,"imageUrl":"http://dummyimage.com/194x229.bmp/ff4444/ffffff","password":"5JybAKMFcdv"},
{"username":"gwashington8","firstName":"Gary","lastName":"Washington","email":"gwashington8@over-blog.com","phoneNumber":"63-(673)499-9259","isUser":false,"imageUrl":"http://dummyimage.com/191x158.jpg/ff4444/ffffff","password":"P0xVclp"},
{"username":"gcarter9","firstName":"George","lastName":"Carter","email":"gcarter9@elegantthemes.com","phoneNumber":"86-(621)821-7483","isUser":false,"imageUrl":"http://dummyimage.com/242x158.jpg/5fa2dd/ffffff","password":"emiVn0r"},
{"username":"dwillisa","firstName":"Dorothy","lastName":"Willis","email":"dwillisa@reuters.com","phoneNumber":"258-(878)683-7243","isUser":false,"imageUrl":"http://dummyimage.com/227x200.bmp/dddddd/000000","password":"9FypCDCAs3i"},
{"username":"bgonzalezb","firstName":"Billy","lastName":"Gonzalez","email":"bgonzalezb@forbes.com","phoneNumber":"372-(221)159-1165","isUser":true,"imageUrl":"http://dummyimage.com/119x100.jpg/dddddd/000000","password":"rnAZYTYliMQ"},
{"username":"dthomasc","firstName":"David","lastName":"Thomas","email":"dthomasc@sourceforge.net","phoneNumber":"86-(678)425-3554","isUser":false,"imageUrl":"http://dummyimage.com/175x233.jpg/ff4444/ffffff","password":"we1QTfauQGE"},
{"username":"dboydd","firstName":"Diana","lastName":"Boyd","email":"dboydd@csmonitor.com","phoneNumber":"48-(859)381-2470","isUser":true,"imageUrl":"http://dummyimage.com/210x171.bmp/cc0000/ffffff","password":"ExBInzq33"},
{"username":"bpricee","firstName":"Barbara","lastName":"Price","email":"bpricee@godaddy.com","phoneNumber":"242-(169)813-4193","isUser":true,"imageUrl":"http://dummyimage.com/121x133.png/dddddd/000000","password":"jO8cHy6"},
{"username":"pcarrollf","firstName":"Peter","lastName":"Carroll","email":"pcarrollf@arstechnica.com","phoneNumber":"63-(603)475-4314","isUser":true,"imageUrl":"http://dummyimage.com/106x169.bmp/5fa2dd/ffffff","password":"lr8t6nGA9"},
{"username":"apriceg","firstName":"Ann","lastName":"Price","email":"apriceg@wsj.com","phoneNumber":"374-(684)283-6166","isUser":true,"imageUrl":"http://dummyimage.com/115x153.bmp/cc0000/ffffff","password":"ENFP9OH"},
{"username":"hstewarth","firstName":"Heather","lastName":"Stewart","email":"hstewarth@mozilla.com","phoneNumber":"7-(729)486-8833","isUser":false,"imageUrl":"http://dummyimage.com/231x179.png/ff4444/ffffff","password":"0TpeLYj2HQ6K"},
{"username":"swelchi","firstName":"Sharon","lastName":"Welch","email":"swelchi@taobao.com","phoneNumber":"358-(763)939-7745","isUser":true,"imageUrl":"http://dummyimage.com/161x112.jpg/ff4444/ffffff","password":"LcggeWX"},
{"username":"vsimpsonj","firstName":"Virginia","lastName":"Simpson","email":"vsimpsonj@storify.com","phoneNumber":"55-(793)273-9552","isUser":true,"imageUrl":"http://dummyimage.com/160x230.png/dddddd/000000","password":"0PYEHwShp7vT"},
{"username":"vwalkerk","firstName":"Virginia","lastName":"Walker","email":"vwalkerk@cmu.edu","phoneNumber":"389-(121)756-1497","isUser":true,"imageUrl":"http://dummyimage.com/169x131.bmp/ff4444/ffffff","password":"pmEJpmzis"},
{"username":"alittlel","firstName":"Antonio","lastName":"Little","email":"alittlel@slashdot.org","phoneNumber":"1-(228)867-2016","isUser":false,"imageUrl":"http://dummyimage.com/182x164.jpg/5fa2dd/ffffff","password":"5M77hI"},
{"username":"chansenm","firstName":"Christina","lastName":"Hansen","email":"chansenm@ucla.edu","phoneNumber":"62-(955)601-9137","isUser":false,"imageUrl":"http://dummyimage.com/114x216.jpg/5fa2dd/ffffff","password":"myI66ryZuD2"},
{"username":"rperryn","firstName":"Rose","lastName":"Perry","email":"rperryn@arizona.edu","phoneNumber":"358-(284)836-1899","isUser":true,"imageUrl":"http://dummyimage.com/220x119.jpg/ff4444/ffffff","password":"1tzusmb"},
{"username":"pgranto","firstName":"Paul","lastName":"Grant","email":"pgranto@over-blog.com","phoneNumber":"62-(664)114-9309","isUser":false,"imageUrl":"http://dummyimage.com/150x130.bmp/5fa2dd/ffffff","password":"bdyA9NzR1x"}]

const dummyMessages = [{"senderId":1,"recipientId":11,"content":"interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor"},
{"senderId":1,"recipientId":11,"content":"a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut"},
{"senderId":1,"recipientId":14,"content":"leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at"},
{"senderId":1,"recipientId":13,"content":"vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna"},
{"senderId":1,"recipientId":19,"content":"nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra"},
{"senderId":1,"recipientId":11,"content":"maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum"},
{"senderId":1,"recipientId":11,"content":"erat nulla tempus vivamus in felis eu sapien cursus vestibulum"},
{"senderId":1,"recipientId":6,"content":"primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse"},
{"senderId":1,"recipientId":6,"content":"dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla"},
{"senderId":1,"recipientId":8,"content":"luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit"},
{"senderId":1,"recipientId":10,"content":"rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat"},
{"senderId":1,"recipientId":20,"content":"quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci"},
{"senderId":1,"recipientId":19,"content":"justo pellentesque viverra pede ac diam cras pellentesque volutpat dui"},
{"senderId":1,"recipientId":11,"content":"in consequat ut nulla sed accumsan felis ut at dolor quis"},
{"senderId":1,"recipientId":19,"content":"et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend"},
{"senderId":1,"recipientId":2,"content":"nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse"},
{"senderId":1,"recipientId":21,"content":"sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique"},
{"senderId":1,"recipientId":17,"content":"adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur"},
{"senderId":1,"recipientId":5,"content":"maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut"},
{"senderId":1,"recipientId":4,"content":"luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in"},
{"senderId":1,"recipientId":3,"content":"metus aenean fermentum donec ut mauris eget massa tempor convallis"},
{"senderId":1,"recipientId":18,"content":"nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy"},
{"senderId":1,"recipientId":12,"content":"erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla"},
{"senderId":1,"recipientId":23,"content":"lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo"},
{"senderId":1,"recipientId":11,"content":"dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed"},
{"senderId":1,"recipientId":2,"content":"mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui"},
{"senderId":1,"recipientId":24,"content":"convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla"},
{"senderId":1,"recipientId":12,"content":"orci mauris lacinia sapien quis libero nullam sit amet turpis elementum"},
{"senderId":1,"recipientId":24,"content":"vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer"},
{"senderId":1,"recipientId":15,"content":"adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci"},
{"senderId":1,"recipientId":2,"content":"augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo"},
{"senderId":1,"recipientId":22,"content":"pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis"},
{"senderId":1,"recipientId":24,"content":"eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget"},
{"senderId":1,"recipientId":4,"content":"ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit"},
{"senderId":1,"recipientId":14,"content":"dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id"},
{"senderId":1,"recipientId":3,"content":"ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus"},
{"senderId":1,"recipientId":18,"content":"molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus"},
{"senderId":1,"recipientId":8,"content":"id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae"},
{"senderId":1,"recipientId":20,"content":"etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus"},
{"senderId":1,"recipientId":8,"content":"tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus"},
{"senderId":1,"recipientId":5,"content":"vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus"},
{"senderId":1,"recipientId":16,"content":"tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi"},
{"senderId":1,"recipientId":16,"content":"at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia"},
{"senderId":1,"recipientId":3,"content":"vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien"},
{"senderId":1,"recipientId":8,"content":"quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet"},
{"senderId":1,"recipientId":25,"content":"duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit"},
{"senderId":1,"recipientId":19,"content":"nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed"},
{"senderId":1,"recipientId":13,"content":"massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit"},
{"senderId":1,"recipientId":19,"content":"pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus"},
{"senderId":1,"recipientId":7,"content":"eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum"},
{"senderId":1,"recipientId":19,"content":"duis bibendum morbi non quam nec dui luctus rutrum nulla"},
{"senderId":1,"recipientId":19,"content":"tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci"},
{"senderId":1,"recipientId":17,"content":"est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus"},
{"senderId":1,"recipientId":16,"content":"sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam"},
{"senderId":1,"recipientId":20,"content":"luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh"},
{"senderId":1,"recipientId":3,"content":"a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem"},
{"senderId":1,"recipientId":25,"content":"purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in"},
{"senderId":1,"recipientId":19,"content":"blandit lacinia erat vestibulum sed magna at nunc commodo placerat"},
{"senderId":1,"recipientId":19,"content":"tortor risus dapibus augue vel accumsan tellus nisi eu orci"},
{"senderId":1,"recipientId":4,"content":"ipsum ac tellus semper interdum mauris ullamcorper purus sit amet"},
{"senderId":1,"recipientId":18,"content":"sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae"},
{"senderId":1,"recipientId":14,"content":"dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis"},
{"senderId":1,"recipientId":3,"content":"ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse"},
{"senderId":1,"recipientId":15,"content":"vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum"},
{"senderId":1,"recipientId":12,"content":"ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique"},
{"senderId":1,"recipientId":24,"content":"lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet"},
{"senderId":1,"recipientId":8,"content":"eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula"},
{"senderId":1,"recipientId":4,"content":"pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur"},
{"senderId":1,"recipientId":3,"content":"euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis"},
{"senderId":1,"recipientId":18,"content":"arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget"},
{"senderId":1,"recipientId":19,"content":"nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque"},
{"senderId":1,"recipientId":20,"content":"vestibulum sit amet cursus id turpis integer aliquet massa id"},
{"senderId":1,"recipientId":7,"content":"amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam"},
{"senderId":1,"recipientId":3,"content":"suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris"},
{"senderId":1,"recipientId":13,"content":"in libero ut massa volutpat convallis morbi odio odio elementum eu interdum"},
{"senderId":1,"recipientId":13,"content":"libero nam dui proin leo odio porttitor id consequat in consequat ut nulla"},
{"senderId":1,"recipientId":22,"content":"ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus"},
{"senderId":1,"recipientId":9,"content":"in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut"},
{"senderId":1,"recipientId":18,"content":"quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia"},
{"senderId":1,"recipientId":5,"content":"cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor"},
{"senderId":1,"recipientId":21,"content":"congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo"},
{"senderId":1,"recipientId":3,"content":"magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien"},
{"senderId":1,"recipientId":15,"content":"justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem"},
{"senderId":1,"recipientId":4,"content":"aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo"},
{"senderId":1,"recipientId":24,"content":"nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque"},
{"senderId":1,"recipientId":4,"content":"in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo"},
{"senderId":1,"recipientId":21,"content":"non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales"},
{"senderId":1,"recipientId":9,"content":"eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc"},
{"senderId":1,"recipientId":9,"content":"vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus"},
{"senderId":1,"recipientId":25,"content":"ante nulla justo aliquam quis turpis eget elit sodales scelerisque"},
{"senderId":1,"recipientId":10,"content":"at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis"},
{"senderId":1,"recipientId":6,"content":"vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy"},
{"senderId":1,"recipientId":6,"content":"turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis"},
{"senderId":1,"recipientId":2,"content":"faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend"},
{"senderId":1,"recipientId":15,"content":"nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat"},
{"senderId":1,"recipientId":16,"content":"augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id"},
{"senderId":1,"recipientId":23,"content":"erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue"},
{"senderId":1,"recipientId":22,"content":"fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies"},
{"senderId":1,"recipientId":8,"content":"tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare"},
{"senderId":1,"recipientId":19,"content":"nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet"},
{"senderId":12,"recipientId":1,"content":"vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer"},
{"senderId":17,"recipientId":1,"content":"nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at"},
{"senderId":10,"recipientId":1,"content":"ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien"},
{"senderId":10,"recipientId":1,"content":"id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque"},
{"senderId":6,"recipientId":1,"content":"sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices"},
{"senderId":8,"recipientId":1,"content":"pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras"},
{"senderId":2,"recipientId":1,"content":"eget eleifend luctus ultricies eu nibh quisque id justo sit"},
{"senderId":3,"recipientId":1,"content":"blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices"},
{"senderId":4,"recipientId":1,"content":"egestas metus aenean fermentum donec ut mauris eget massa tempor convallis"},
{"senderId":12,"recipientId":1,"content":"sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed"},
{"senderId":5,"recipientId":1,"content":"pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse"},
{"senderId":15,"recipientId":1,"content":"sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non"},
{"senderId":6,"recipientId":1,"content":"sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel"},
{"senderId":16,"recipientId":1,"content":"venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue"},
{"senderId":23,"recipientId":1,"content":"massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis"},
{"senderId":25,"recipientId":1,"content":"porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac"},
{"senderId":10,"recipientId":1,"content":"risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl"},
{"senderId":7,"recipientId":1,"content":"erat quisque erat eros viverra eget congue eget semper rutrum"},
{"senderId":19,"recipientId":1,"content":"integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus"},
{"senderId":8,"recipientId":1,"content":"non lectus aliquam sit amet diam in magna bibendum imperdiet"},
{"senderId":3,"recipientId":1,"content":"luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum"},
{"senderId":20,"recipientId":1,"content":"sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum"},
{"senderId":21,"recipientId":1,"content":"mauris vulputate elementum nullam varius nulla facilisi cras non velit nec"},
{"senderId":5,"recipientId":1,"content":"vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque"},
{"senderId":13,"recipientId":1,"content":"ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit"},
{"senderId":18,"recipientId":1,"content":"sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam"},
{"senderId":17,"recipientId":1,"content":"amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu"},
{"senderId":22,"recipientId":1,"content":"turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis"},
{"senderId":6,"recipientId":1,"content":"nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo"},
{"senderId":19,"recipientId":1,"content":"volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse"},
{"senderId":15,"recipientId":1,"content":"erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus"},
{"senderId":4,"recipientId":1,"content":"at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla"},
{"senderId":21,"recipientId":1,"content":"odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut"},
{"senderId":5,"recipientId":1,"content":"in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac"},
{"senderId":4,"recipientId":1,"content":"magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien"},
{"senderId":13,"recipientId":1,"content":"vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas"},
{"senderId":19,"recipientId":1,"content":"lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat"},
{"senderId":19,"recipientId":1,"content":"duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend"},
{"senderId":16,"recipientId":1,"content":"sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet"},
{"senderId":12,"recipientId":1,"content":"justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id"},
{"senderId":19,"recipientId":1,"content":"mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus"},
{"senderId":25,"recipientId":1,"content":"tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus"},
{"senderId":6,"recipientId":1,"content":"duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis"},
{"senderId":6,"recipientId":1,"content":"varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero"},
{"senderId":6,"recipientId":1,"content":"in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum"},
{"senderId":12,"recipientId":1,"content":"libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis"},
{"senderId":23,"recipientId":1,"content":"fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc"},
{"senderId":15,"recipientId":1,"content":"luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat"},
{"senderId":6,"recipientId":1,"content":"vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing"},
{"senderId":24,"recipientId":1,"content":"luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat"},
{"senderId":14,"recipientId":1,"content":"mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec"},
{"senderId":9,"recipientId":1,"content":"non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante"},
{"senderId":7,"recipientId":1,"content":"suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus"},
{"senderId":18,"recipientId":1,"content":"ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit"},
{"senderId":25,"recipientId":1,"content":"natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis"},
{"senderId":23,"recipientId":1,"content":"vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum"},
{"senderId":9,"recipientId":1,"content":"leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in"},
{"senderId":2,"recipientId":1,"content":"ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris"},
{"senderId":6,"recipientId":1,"content":"placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula"},
{"senderId":5,"recipientId":1,"content":"turpis a pede posuere nonummy integer non velit donec diam neque vestibulum"},
{"senderId":10,"recipientId":1,"content":"nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque"},
{"senderId":12,"recipientId":1,"content":"sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui"},
{"senderId":2,"recipientId":1,"content":"rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia"},
{"senderId":7,"recipientId":1,"content":"adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at"},
{"senderId":13,"recipientId":1,"content":"libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt"},
{"senderId":9,"recipientId":1,"content":"pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa"},
{"senderId":9,"recipientId":1,"content":"lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget"},
{"senderId":23,"recipientId":1,"content":"erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in"},
{"senderId":10,"recipientId":1,"content":"ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer"},
{"senderId":23,"recipientId":1,"content":"quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel"},
{"senderId":21,"recipientId":1,"content":"est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis"},
{"senderId":5,"recipientId":1,"content":"nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus"},
{"senderId":6,"recipientId":1,"content":"eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien"},
{"senderId":20,"recipientId":1,"content":"viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus"},
{"senderId":7,"recipientId":1,"content":"feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac"},
{"senderId":3,"recipientId":1,"content":"rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit"},
{"senderId":22,"recipientId":1,"content":"massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit"},
{"senderId":16,"recipientId":1,"content":"magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien"},
{"senderId":22,"recipientId":1,"content":"felis eu sapien cursus vestibulum proin eu mi nulla ac"},
{"senderId":25,"recipientId":1,"content":"sit amet lobortis sapien sapien non mi integer ac neque duis bibendum"},
{"senderId":17,"recipientId":1,"content":"posuere nonummy integer non velit donec diam neque vestibulum eget vulputate"},
{"senderId":2,"recipientId":1,"content":"odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim"},
{"senderId":23,"recipientId":1,"content":"vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere"},
{"senderId":16,"recipientId":1,"content":"aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus"},
{"senderId":2,"recipientId":1,"content":"parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus"},
{"senderId":10,"recipientId":1,"content":"sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi"},
{"senderId":8,"recipientId":1,"content":"in consequat ut nulla sed accumsan felis ut at dolor"},
{"senderId":13,"recipientId":1,"content":"phasellus in felis donec semper sapien a libero nam dui proin leo"},
{"senderId":6,"recipientId":1,"content":"tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac"},
{"senderId":21,"recipientId":1,"content":"eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus"},
{"senderId":14,"recipientId":1,"content":"eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut"},
{"senderId":6,"recipientId":1,"content":"turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in"},
{"senderId":24,"recipientId":1,"content":"risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis"},
{"senderId":11,"recipientId":1,"content":"sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere"},
{"senderId":8,"recipientId":1,"content":"est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus"},
{"senderId":20,"recipientId":1,"content":"vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod"},
{"senderId":9,"recipientId":1,"content":"nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan"},
{"senderId":8,"recipientId":1,"content":"est phasellus sit amet erat nulla tempus vivamus in felis"},
{"senderId":12,"recipientId":1,"content":"aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi"},
{"senderId":15,"recipientId":1,"content":"dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam"}]


module.exports = { dummyUser, dummyMessages };
