/*eslint comma-spacing: 0, key-spacing: 0, quotes: 0, quote-props: 0 */

const dummyUser = [{"username":"ak123","ZFIRSTNAME":"a","ZLASTNAME":"k","email":"ak123@ak123.com","ZFULLNUMBER":"111-111-1111","isUser":true,"imageUrl":"https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAikAAAAJGNkZGExNzM1LWRhYTUtNGQ3ZC05MTA5LWMwNzY0MWQxMmRjYw.jpg","password":"1234"},
{"username":"dammdaniel","ZFIRSTNAME":"damm","ZLASTNAME":"daniel","email":"dammdaniel@whatarethose.com","ZFULLNUMBER":"222-222-2222","isUser":true,"isAdmin":true,"imageUrl":"http://i.dailymail.co.uk/i/pix/2016/02/26/21/31734FC200000578-0-Popular_The_original_clip_has_been_retweeted_over_260_000_times_-m-67_1456522238590.jpg","password":"1234"},
{"username":"menaka","ZFIRSTNAME":"menaka","ZLASTNAME":"menaka","email":"menaka@idareyoutosaymynamewrong.lol","ZFULLNUMBER":"333-333-3333","isUser":true,"imageUrl":"https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAASDAAAAJGY4MmFjNTg5LTEzMzItNDAwYy1hMzJkLTczNjM4NTgwMmJjNw.jpg","password":"1234"},
{"username":"bambam","ZFIRSTNAME":"bambam","ZLASTNAME":"bambam","email":"bambam@bambam.com","ZFULLNUMBER":"555-555-5555","isUser":true,"imageUrl":"http://dummyimage.com/153x114.bmp/ff4444/ffffff","password":"bambam"},
{"ZFIRSTNAME":"Leila","ZLASTNAME":"Karalanian","email":"Leila@issodarncute.com","ZFULLNUMBER":"777-777-7777","isUser":false},
{"ZFIRSTNAME":"Rachel","ZLASTNAME":"Armstrong","ZFULLNUMBER":"55-(222)608-4605"},
{"ZFIRSTNAME":"Carol","ZLASTNAME":"Ruiz","ZFULLNUMBER":"86-(396)850-2099"},
{"ZFIRSTNAME":"Catherine","ZLASTNAME":"Griffin","ZFULLNUMBER":"55-(150)285-2050"},
{"ZFIRSTNAME":"Stephanie","ZLASTNAME":"Grant","ZFULLNUMBER":"48-(494)214-8714"},
{"ZFIRSTNAME":"Heather","ZLASTNAME":"Gonzales","ZFULLNUMBER":"358-(150)444-2844"},
{"ZFIRSTNAME":"Roger","ZLASTNAME":"Allen","ZFULLNUMBER":"46-(701)237-3051"},
{"ZFIRSTNAME":"Frances","ZLASTNAME":"Mills","ZFULLNUMBER":"63-(418)589-9155"},
{"ZFIRSTNAME":"Amy","ZLASTNAME":"Nichols","ZFULLNUMBER":"86-(690)561-1202"},
{"ZFIRSTNAME":"Betty","ZLASTNAME":"Morgan","ZFULLNUMBER":"48-(677)738-7416"},
{"ZFIRSTNAME":"Richard","ZLASTNAME":"Ramirez","ZFULLNUMBER":"7-(874)987-7180"},
{"ZFIRSTNAME":"Nicholas","ZLASTNAME":"West","ZFULLNUMBER":"98-(597)819-6061"},
{"ZFIRSTNAME":"Denise","ZLASTNAME":"Coleman","ZFULLNUMBER":"237-(958)972-6253"},
{"ZFIRSTNAME":"Marie","ZLASTNAME":"Reed","ZFULLNUMBER":"46-(841)908-7476"},
{"ZFIRSTNAME":"Julia","ZLASTNAME":"Alexander","ZFULLNUMBER":"86-(200)938-9457"},
{"ZFIRSTNAME":"Theresa","ZLASTNAME":"Lopez","ZFULLNUMBER":"53-(132)565-7846"},
{"ZFIRSTNAME":"Terry","ZLASTNAME":"Carr","ZFULLNUMBER":"34-(112)651-6712"},
{"ZFIRSTNAME":"Marie","ZLASTNAME":"Morales","ZFULLNUMBER":"353-(286)604-2271"},
{"ZFIRSTNAME":"Judy","ZLASTNAME":"Morales","ZFULLNUMBER":"86-(737)841-3570"},
{"ZFIRSTNAME":"Heather","ZLASTNAME":"Hicks","ZFULLNUMBER":"1-(176)450-2568"},
{"ZFIRSTNAME":"Joseph","ZLASTNAME":"Lawrence","ZFULLNUMBER":"502-(770)922-9429"},
{"ZFIRSTNAME":"Steve","ZLASTNAME":"Carpenter","ZFULLNUMBER":"62-(748)327-3884"},
{"ZFIRSTNAME":"Raymond","ZLASTNAME":"Clark","ZFULLNUMBER":"46-(411)224-2351"},
{"ZFIRSTNAME":"Clarence","ZLASTNAME":"Fisher","ZFULLNUMBER":"33-(409)900-5897"},
{"ZFIRSTNAME":"Amanda","ZLASTNAME":"Stevens","ZFULLNUMBER":"86-(633)608-9447"},
{"ZFIRSTNAME":"Kelly","ZLASTNAME":"Martin","ZFULLNUMBER":"86-(663)381-6704"}]

const dummyMessages = [{"content":"cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"nec sem duis aliquam convallis nunc proin at turpis a","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"non mi integer ac neque duis bibendum morbi non quam nec dui","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"ligula vehicula consequat morbi a ipsum integer a nibh in quis justo","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"duis aliquam convallis nunc proin at turpis a pede posuere nonummy","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"nunc proin at turpis a pede posuere nonummy integer non velit donec diam","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"risus praesent lectus vestibulum quam sapien varius ut blandit non","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"molestie lorem quisque ut erat curabitur gravida nisi at nibh","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"purus aliquet at feugiat non pretium quis lectus suspendisse potenti in","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"tellus nisi eu orci mauris lacinia sapien quis libero nullam","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"at velit eu est congue elementum in hac habitasse platea dictumst morbi","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"porttitor pede justo eu massa donec dapibus duis at velit eu","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"eleifend pede libero quis orci nullam molestie nibh in lectus","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"est phasellus sit amet erat nulla tempus vivamus in felis eu sapien","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"neque duis bibendum morbi non quam nec dui luctus rutrum nulla","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"justo morbi ut odio cras mi pede malesuada in imperdiet et","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"orci luctus et ultrices posuere cubilia curae duis faucibus accumsan","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"a odio in hac habitasse platea dictumst maecenas ut massa quis","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"cursus vestibulum proin eu mi nulla ac enim in tempor","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"semper rutrum nulla nunc purus phasellus in felis donec semper sapien a","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"urna ut tellus nulla ut erat id mauris vulputate elementum","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"sapien sapien non mi integer ac neque duis bibendum morbi non quam nec","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'},
{"content":"nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"i think im missing a message for 200","date":0,"is_sender":0,"ZFULLNUMBER":'777-777-7777'},
{"content":"eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula","date":0,"is_sender":1,"ZFULLNUMBER":'777-777-7777'}]


module.exports = { dummyUser, dummyMessages };
